### PR TITLE
Update tasks.json and other PATH fixes

### PR DESCRIPTION
**Pull request by austince**
This is a start to the fix I was thinking about for #8 but I haven't had time to test it. I'll do that in the next few days but wanted to get your feedback before jumping fully!

### CODE REVIEW

**Comment by AvinZarlez** [comment]
Looking good so far! Thank you so much for improving this/contributing!

**Comment by AvinZarlez** [comment]
(I didn't test either, just looked through FYI. I see what you're trying to set up and makes sense)

**Comment by austince** [comment]
Thanks @TobiahZ! Do you have a good system/process for testing?

**Comment by AvinZarlez** [comment]
I have a unit test system set up, but sadly I never actually made the unit tests. https://github.com/TobiahZ/processing-vscode/blob/master/test/extension.test.ts

Even if not going full proper unit tests, we should attempt to crowd source testing it on Mac and Windows at the very least. Make sure common folder structure doesn't break it, or various task file tweaks break it. etc.

**Comment by austince** [comment]
Ok great, I'll work on some unit tests and can test on a Windows machine sometime this week.

**Comment by austince** [comment]
We should also probably move to config version 2.0 while we're updating this.

I'm not sure if this is better or worse than using the `windows`, `linux`, `osx` override keys as shown here: https://code.visualstudio.com/docs/editor/tasks#_operating-system-specific-properties

**Comment by austince** [comment]
Hey @TobiahZ, I think this is our best bet for now. I'd like to upgrade to the newest versions of everything and then rework a lot of the filesystem stuff. I'll put in a PR for upgrading soon if that sounds good to you!

**Comment by AvinZarlez** [comment]
Makes sense to me! I'm traveling right now, but will try to open VSCode and double check "works on my machine" for any issues, and if not merge and push to store.

**Comment by austince** [comment]
Sounds good, safe travels! 👍🏼

**Comment by AvinZarlez** [comment]
I'm sorry I still haven't had time to address this! Still traveling (in the midst of non-stop travel for all of March) and haven't had the moment to check yet. I didn't forget! I'll try to get it done sometime this week if I can.

**Comment by austince** [comment]
No worries, I'm actually just getting back from a trip myself.

**Comment by AvinZarlez** [comment]
The Task doesn't return a nice error message for some reason. Works fine if you have processing in your path. If you don't, and run the task file from VSCode, you get the error message. If you do the run task command, no error message at all. Not sure why it isn't being captured. But otherwise seems fine to merge in

**Pull request merged**
