### PR TITLE
chore: Update dependencies, add linting, etc.

### PR DESCRIPTION
**Pull request by austince**
Hey, I've gotten pretty busy myself lately but I did put in some work to update the dependencies a while back. It's not perfect but a good start. I followed some VSCode official upgrade guides and looked at official VSCode extensions, I'll find the links later. Figured I should at least put in the PR so the work doesn't go to waste.  Also updates travis script in line with their recommendations.

### CODE REVIEW

**Comment by austince** [comment]
This might also be a good tool for this purpose: https://github.com/marketplace/dependabot

**Comment by AvinZarlez** [comment]
Didn't test, but changes make sense. I haven't looked at the extension docs in a bit so I assume matches up with what is recommended now.

Is there more you'd want to work on with this, or are these changes ready?


That bot seems useful! Looking into it now.

**Comment by austince** [comment]
Yeah I am pretty sure that it is ready to merge, but not sure if any of the extension is deprecated. I only updated the dependencies but didn't look at how the VS Code API changed.

**Comment by AvinZarlez** [comment]
Can you do me a favor and run through and test if every feature still works after these changes?

Ought to set up unit tests but right now still need to manually test everything
________________________________

**Comment by austince** [comment]
Hey, so sorry! I've been finishing up school and starting work - thanks for merging / keep this in the works and hope you're doing well!

**Comment by AvinZarlez** [comment]
All good! I did similar updates to my Unity Tools extension so doing the same to this now.

Have to update some of the scripts using some deprecated variables. Doing that now

-Tobiah Zarlez

Sent from Outlook for Android

________________________________

**Pull request merged**
